### ISSUE TITLE
require('y-xml') doesn't return a function.

### ISSUE THREAD

**Issue by druuu** [y-js/y-xml#9]
Loading y-xml using `require('y-xml')` returns 'undefined', so when I use `require('y-xml')(Y)` it throws error.

I'm trying to implement [xml-example](http://y-js.org/xml-example.html) by using requirejs.

I am able to load y-memory, y-array, y-map and all other modules and initialize with 'Y' without problems, but can't do that for y-xml.

I have [github-repo](https://github.com/druuu/www) which has y-xml implementation, also I have created a [github-page](https://druuu.github.io/www/) reproduce the error.

Thank you for your great work.

**Comment by druuu** [comment]
Looks like there is version mismatch.
After using the latest versions, it has resolved.

**Comment by druuu** [comment]
@dmonad i have found your [webmakers-demo](https://github.com/dmonad/webmakers-demo) which uses y-xml. I have removed the url for websockets-server to use default one, the url provided in webmakers-demo 'https://y-websockets-server-karpclbnxp.now.sh' isn't working.

Unfortunately the demo doesn't work, it throws error: `Uncaught TypeError: Super expression must either be null or a function, not undefined` in y-array.js

it will be really helpful if you could provide a simple demo implementing y-xml with requirejs.

thank you

**Comment by druuu** [comment]
**workaround**
use browserify to bundle all the modules, this way require('y-xml')(Y) won't throw error.

**Comment by dmonad** [comment]
Hey, slowly resolving issues. 

I think you already found this out. Yjs is only available as a npm module. You need something like browserify or webpack to use it in a website (which is sadly the standard now)
